theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
feed:
  categories:
    - personal
    - community
title: Dan Pilch Blog
description: Personal and Professional blog
author: Dan Pilch
